MERGE INSTALLING NODEJS WITH VOLTA && FIX SUDO CLEAN:
AdrianWeaver/transcendence pull request #36
Opened 2023-08-17 15:28 UTC by Elena-Lou

Both Dockerfiles install the latest LTS version of nodejs through volta to improve build time
Close #30 

Clean rule in front/Makefile required sudo rights : it was unnecessary and could present an issue - at school, for instance, since we do not have sudo rights - it is removed.

2023-08-18 16:58 UTC, Elena-Lou commented
- [ ] need to run npm install from makefile after launching the container 
- [ ]  check npm permissions : node user ?

2023-08-21 18:45 UTC, Keeghaan approved these changes
super !

2023-08-22 11:34 UTC, nicolkaver commented
Hello, thank you, but I am a little confused, how can we then make clean on our VM? I just tried and I have permission denied from everywhere

2023-08-22 13:12 UTC, Elena-Lou commented
> Hello, thank you, but I am a little confused, how can we then make clean on our VM? I just tried and I have permission denied from everywhere

@nicolkaver Hmmm the pb is that we won´t be able to sudo at school

2023-08-22 16:41 UTC, apayetRun requested changes
You are doing a good job !!
Just small fix to validate this P.R.
I request change because global package is not installed in front/Makefile
```
install_global:
	@echo "cd /app && npm install" | docker exec -i frontend /bin/bash
```

for now when I launch it says to me **Volta error: Could not locate executable `vite` in your project.**

2023-08-23 17:01 UTC, AdrianWeaver approved these changes

2023-08-24 06:45 UTC, AdrianWeaver commented on backend/Makefile
> +	@echo "cd /app && npm install" | docker exec -i backend /bin/bash
@apayetRun @Elena-Lou I let you sort this out so we can resolve and merge 🤓

2023-08-24 07:06 UTC, apayetRun approved these changes
Great Job !

2023-08-24 07:07 UTC, merged